export const THEME = 'THEME'
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const COLLAPSE_MENU = 'COLLAPSE_MENU'
export const MENU_TRANSITION = 'MENU_TRANSITION'
export const SCROLL_MENU = 'SCROLL_MENU'
