export const initState = {
  backImage: null,
  backSlider: false,
  rightImage: null,
  hasBackImage: null,
  hiddenDown: false,
  isMenu: false,
  jumboCount: 0,
  previousTheme: 'white',
  sicgrid: 'left',
  storedTheme: 'white',
  worksFilter: null,
  worksFiltersOpen: false,
  worksGrid: true,
}
