export const initState = {
  backImage: null,
  backSlider: false,
  rightImage: null,
  collapsedMenu: false,
  collapseTransition: false,
  hiddenMenu: false,
  isMenu: false,
  jumboCount: 0,
  previousTheme: 'white',
  storedTheme: 'white',
  worksFilter: null,
  worksFiltersOpen: false,
  worksGrid: true,
}